name: docker-compose

on:
  push:
    branches:
      - chore/actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compose-run
        shell: bash
        run: |
          docker-compose build
          docker-compose up -d
          docker exec -it youthsignalstail-gamerscom_nuxtjs_1 bash -c "ls && cd src/ && ls"
